server:
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/white_jotter?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: mysql8.0
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none